app:
  restart: always
  build: .
  volumes:
     - /opt/appserver/webapps
webserver:
  restart: always
  image: wagner83104/webserver:master
  volumes_from:
    - app
message-queue:
  restart: always
  image: wagner83104/message-queue:master
  volumes_from:
    - app
ssh-server:
  restart: always
  image: wagner83104/ssh-server:master
  volumes_from:
    - app