appdata:
  image: wagner83104/dist:1.1.1-alpha7
  container_name: appdata
  volumes:
    - /opt/appserver/webapps

webserver:
  restart: always
  container_name: webserver
  image: wagner83104/dist:1.1.1-alpha7
  links:
    - mysql
  volumes_from:
    - appdata
  volumes:
    - ./docker/opt/appserver/etc/appserver/webserver.xml:/opt/appserver/etc/appserver/appserver.xml

servlet-engine:
  restart: always
  container_name: servlet-engine
  image: wagner83104/dist:1.1.1-alpha7
  links:
    - mysql
    - message-queue
    - persistence-container
  volumes_from:
    - appdata
  volumes:
    - ./docker/opt/appserver/etc/appserver/servlet-engine.xml:/opt/appserver/etc/appserver/appserver.xml

message-queue:
  restart: always
  container_name: message-queue
  image: wagner83104/dist:1.1.1-alpha7
  links:
    - persistence-container
  volumes_from:
    - appdata
  volumes:
    - ./docker/opt/appserver/etc/appserver/message-queue.xml:/opt/appserver/etc/appserver/appserver.xml

persistence-container:
  restart: always
  container_name: persistence-container
  image: wagner83104/dist:1.1.1-alpha7
  links:
    - mysql
  volumes_from:
    - appdata
  volumes:
    - ./docker/opt/appserver/etc/appserver/persistence-container.xml:/opt/appserver/etc/appserver/appserver.xml

mysql:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: 'appserver.i0'
    MYSQL_USER: 'appserver'
    MYSQL_PASSWORD: 'appserver.i0'
    MYSQL_DATABASE: 'appserver_ApplicationServer'
  volumes_from:
    - appdata